

# Site Settings
title: 						"DAESHU"
email: 						"daniel@escobar.eu.org"
description: 				"Este blog es la continuación de las publicaciones de antaño Mal Signo e Insolación, alojado en Github"
baseurl: 					""
url: 						"https://daeshu.github.io/a/"
logourl: 					"/assets/img/bloglogo.jpg"		
fa-logo: 					"fa-bookmark-o"
paginate: 					5


# Author Settings
author_name: 				"DAESHU"
author_url: 				""
author_bio: 				"Publicado por Daniel."
author_email: 				"info@escobar.eu.org"
author_image: 				"/assets/img/authorimage.jpg"


# Social Settings
twitter_url: 				"http://twitter.com/DanielEscobarW"
facebook_url: 				"http://facebook.com"
github_url:  				"http://github.com"
youtube_url:  				"http://youtube.com"
dribbble_url:  				"http://dribbble.com"
googleplus_url: 			"http://google.com/plus"
instagram_url:  			"http://instagram.com"
pinterest_url:  			"http://pinterest.com"
linkedin_url:  				"http://linkedin.com"


# Theme Settings
theme_disqus_shortname: 	"daeshu"
theme_google_comments: 		false
theme_analytics_id: 		"UA-28282324-1"
theme_analytics_domain: 	"daniel.escobar.eu.org"
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

