

# Site Settings
title: 						"Escobar"
email: 						"info@escobar.eu.org"
description: 				"Memorias de un grano de arena en un día soleado, en las costas de algún remoto lugar del planeta tierra."
baseurl: 					"https://blog.escobar.eu.org"
url: 						"https://blog.escobar.eu.org"
logourl: 					"https://sites.google.com/site/danielescobarweb/bloglogo.jpg"		
fa-logo: 					"fa-bookmark-o"
paginate: 					5


# Author Settings
author_name: 				"Escobar"
author_url: 				"https://blog.escobar.eu.org"
author_bio: 				"Memorias de un grano de arena en un día soleado, en las costas de algún remoto lugar del planeta tierra."
author_email: 				"info@escobar.eu.org"
author_image: 				"https://sites.google.com/site/danielescobarweb/authorimage.jpg"


# Social Settings
twitter_url: 				"http://twitter.com/DanielEscobarW"
facebook_url: 				"http://facebook.com"
github_url:  				"http://github.com"
youtube_url:  				"http://youtube.com"
googleplus_url: 			"http://google.com/plus"
instagram_url:  			"http://instagram.com"
pinterest_url:  			"http://pinterest.com"
linkedin_url:  				"http://linkedin.com"


# Theme Settings
theme_disqus_shortname: 	"escobar"
theme_google_comments: 		false
theme_analytics_id: 		"UA-28282324-1"
theme_analytics_domain: 	"https://blog.escobar.eu.org"
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

